apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: meu-app-echo
  template:
    metadata:
      labels:
        app: meu-app-echo
    spec:
      containers:
      - name: echo-container
        image: hashicorp/http-echo
        args:
          - "-text=Ola! Eu sou a Pod: $(MY_POD_NAME)"
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: meu-app-echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: LoadBalancer
