apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 5 # Aqui definimos 3 Pods para o seu clister!
  selector:
    matchLabels:
      app: meu-nginx
  template:
    metadata:
      labels:
        app: meu-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: meu-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
